apiVersion: apps/v1
kind: Deployment
metadata:
  name: exam-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exam-api
  template:
    metadata:
      labels:
        app: exam-api
    spec:
      containers:
        - name: exam-api
          image: ghcr.io/bsmsus/exam-api:8f58fc76c254602184a1631793c0726dca9e7f48
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: postgresql://exam:exam@db:5432/exam?serverVersion=16
